name: Github Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-build:
    name: Create ${{ matrix.target }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [Windows, Linux]
        include:
          - os: windows-latest
            target: Windows
          - os: ubuntu-latest
            target: Linux
      fail-fast: false
    steps:
      - run: echo "hello world" >hello-${{matrix.target}}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ./hello-${{ matrix.target }}.txt
      - run: ls -l -R


  publish-canary:
    name: Publish Canary
    if: github.ref == 'refs/heads/main'
    needs: create-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date)"
      - uses: actions/download-artifact@v3
      - run: ls -l -R

      - name: Delete previous canary build
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: canary
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

      - name: Publish release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: canary
          name: Chaldea Preview
          body: Built at ${{ steps.get-date.outputs.date }}
          draft: false
          prerelease: true
          artifacts: "hello-*"
