# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:

jobs:
  atlas:
    runs-on: ubuntu-latest
    env:
      output_dir: 'data/'
    steps:
      - uses: actions/checkout@v2

#       - name: Setup Python 3.10
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.10'
#           cache: 'pip'
      - run: |
          echo '${{ github.event.client_payload }}"'
          echo '${{ toJson(github.event.client_payload) }}'

          echo '${{ github.event.client_payload }}' >> payload1.txt
          echo '${{ toJson(github.event.client_payload) }}' >> payload2.txt
          
          cat payload1.txt
          cat payload2.txt
          
