name: Github Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-build:
    name: Create ${{ matrix.target }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [Linux2, Linux]
        include:
          - os: ubuntu-latest
            target: Linux
          - os: windows-latest
            target: Windows
      fail-fast: false
    steps:
      - run: echo "hello world" >hello-${{matrix.target}}.txt
      - name: Get Version
        shell: bash
        run: |
          echo ${{ matrix.os }}
          if [ "${{ startsWith(github.ref, 'refs/tags/v') }}" = "true" ]; then
              echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          else
              echo "VERSION=preview" >> $GITHUB_ENV
          fi
          echo "VERSION = $VERSION"

