name: Deploy to Github Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  draft-release:
    name: Draft Github release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      html_url: ${{ steps.create_release.outputs.html_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date)"

      - name: Delete previous canary build
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: canary
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

      - name: Draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        with:
          tag_name: canary
          release_name: Chaldea Preview
          body: "Built at: ${{ steps.get-date.outputs.date }}"
          draft: true
          prerelease: true

  publish-release:
    needs: draft-release
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.draft-release.outputs.release_id }}
          echo ${{ needs.draft-release.outputs.upload_url }}
          echo ${{ needs.draft-release.outputs.html_url }}
          
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        with:
          release_id: ${{ needs.draft-release.outputs.release_id }}
