name: Github Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Downgrade zstd
        run: |
          zstd --version
          wget -O zstd152.tar.gz  https://github.com/facebook/zstd/releases/download/v1.5.2/zstd-1.5.2.tar.gz
          tar -xvf zstd152.tar.gz
          cd zstd152
          make install
          zstd --version
